### PR TITLE
User management sanele

### PR DESCRIPTION
**Pull request by Technocoder7**
Added the Frontend for User Management

### CODE REVIEW

**Comment by terrameijar** [comment]
@Technocoder7 your PR has conflicts with the base branch. You'll need to fix these before we can merge it.

**Comment by Technocoder7** [comment]
Ijust saw the project structure changed, the backend and frontend folders
are now in the same branch, so should i branch from main and then copy my
code from my branch into the new branch then you try merging?

**Comment by terrameijar** [comment]
@Technocoder7 did you get a chance to resolve the issues? The fix is to pull down the latest changes on main and merge the main branch to this one.

**Comment by terrameijar** [comment]
@Technocoder7 I just merged main into this PR so it looks good now.

**Pull request merged**
